const HEROES = [
    { name: "D.Va", role: "Tank", image: "images/tank/dva.png" },
    { name: "Doomfist", role: "Tank", image: "images/tank/doomfist.png" },
    { name: "Hazard", role: "Tank", image: "images/tank/hazard.png" },
    { name: "Winston", role: "Tank", image: "images/tank/winston.png" },
    { name: "Wrecking Ball", role: "Tank", image: "images/tank/wrecking_ball.png" },
    { name: "Mauga", role: "Tank", image: "images/tank/mauga.png" },
    { name: "Orisa", role: "Tank", image: "images/tank/orisa.png" },
    { name: "Roadhog", role: "Tank", image: "images/tank/roadhog.png" },
    { name: "Zarya", role: "Tank", image: "images/tank/zarya.png" },
    { name: "Domina", role: "Tank", image: "images/tank/domina.png" },
    { name: "Junkerqueen", role: "Tank", image: "images/tank/junkerqueen.png" },
    { name: "Ramattra", role: "Tank", image: "images/tank/ramattra.png" },
    { name: "Reinhardt", role: "Tank", image: "images/tank/reinhardt.png" },
    { name: "Sigma", role: "Tank", image: "images/tank/sigma.png" },

    { name: "Bastion", role: "Damage", image: "images/damage/bastion.png" },
    { name: "Emre", role: "Damage", image: "images/damage/emre.png" },
    { name: "Junkrat", role: "Damage", image: "images/damage/junkrat.png" },
    { name: "Mei", role: "Damage", image: "images/damage/mei.png" },
    { name: "Soldier 76", role: "Damage", image: "images/damage/soldier_76.png" },
    { name: "Symmetra", role: "Damage", image: "images/damage/symmetra.png" },
    { name: "Torbjörn", role: "Damage", image: "images/damage/torbjörn.png" },
    { name: "Ashe", role: "Damage", image: "images/damage/ashe.png" },
    { name: "Cassidy", role: "Damage", image: "images/damage/cassidy.png" },
    { name: "Hanzo", role: "Damage",image: "images/damage/hanzo.png" },
    { name: "Sojourn", role: "Damage", image: "images/damage/sojourn.png" },
    { name: "Widowmaker", role: "Damage", image: "images/damage/widowmaker.png" },
    { name: "Anran", role: "Damage", image: "images/damage/anran.png" },
    { name: "Genji", role: "Damage", image: "images/damage/genji.png" },
    { name: "Reaper", role: "Damage", image: "images/damage/reaper.png" },
    { name: "Tracer", role: "Damage", image: "images/damage/tracer.png" },
    { name: "Vendetta", role: "Damage", image: "images/damage/vendetta.png" },
    { name: "Venture", role: "Damage", image: "images/damage/venture.png" },
    { name: "Echo", role: "Damage", image: "images/damage/echo.png" },
    { name: "Freja", role: "Damage", image: "images/damage/freja.png" },
    { name: "Pharah", role: "Damage", image: "images/damage/pharah.png" },
    { name: "Sierra", role: "Damage", image: "images/damage/sierra.png" },
    { name: "Sombra", role: "Damage", image: "images/damage/sombra.png" },

    { name: "Ana", role: "Support", image: "images/support/ana.png" },
    { name: "Baptiste", role: "Support", image: "images/support/baptiste.png" },
    { name: "Jetpack Cat", role: "Support", image: "images/support/jetpack_cat.png" },
    { name: "Lucio", role: "Support", image: "images/support/lucio.png" },
    { name: "Zenyatta", role: "Support", image: "images/support/zenyatta.png" },
    { name: "Kiriko", role: "Support", image: "images/support/kiriko.png" },
    { name: "Lifeweaver", role: "Support", image: "images/support/lifeweaver.png" },
    { name: "Mercy", role: "Support", image: "images/support/mercy.png" },
    { name: "Moira", role: "Support", image: "images/support/moira.png" },
    { name: "Brigitte", role: "Support", image: "images/support/brigitte.png" },
    { name: "Illari", role: "Support", image: "images/support/illari.png" },
    { name: "Juno", role: "Support", image: "images/support/juno.png" },
    { name: "Mizuki", role: "Support", image: "images/support/mizuki.png" },
    { name: "Wuyang", role: "Support", image: "images/support/wuyang.png" }    

]